from .usuarios import Usuarios as UsuariosRec
from .usuarios import Usuario as UsuarioRec
from .usuarios import UsuariosAlumnos as UsrsAlumnosRec
from .usuarios import UsuarioProfesor as UsrProfesorRec
from .usuarios import UsuarioAlumno as UsrAlumnoRec
from .planificacion import PlanificacionAlumno as PlanAlumnoRec
from .planificacion import PlanificacionProfesor as PlanProfesorRec
from .planificacion import PlanificacionesProfesores as PlansProfesoresRec
from .profesor import ProfesorClases as ProfesorClasesRec
from .pago import Pago as PagoRec
from .pago import Pagos as PagosRec
from .login import Login as LoginRec
from .clases import Clase_R as ClaseRec
from .clases import Clases_R as ClasesRec
